import { Mode } from "./EventCode";

interface Dictionary<T> {
  [Key: number]: T;
}

export default class Station {
  public static dataTrain: Dictionary<Dictionary<string>> = {
    1: {
      0: "Châtelet-Les Halles",
      1: "Châtelet-Les Halles",
      7: "Luxembourg",
      10: "Châtelet-Les Halles",
    },
    3: {
      0: "Saint-Michel Notre-Dame",
    },
    6: {
      0: "Auber",
    },
    9: {
      13: "Gare de Lyon",
    },
    14: {
      4: "Cité Universitaire",
    },
    15: {
      12: "Port Royal",
      13: "Denfert-Rochereau",
    },
    16: {
      1: "Nation",
      2: "Fontenay-sous-Bois|Vincennes",
      3: "Joinville-le-Pont|Nogent-sur-Marne",
      4: "Saint-Maur Créteil",
      5: "Le Parc de Saint-Maur",
      6: "Champigny",
      7: "La Varenne-Chennevières",
      8: "Boissy-Saint-Léger|Sucy Bonneuil",
    },
    17: {
      1: "Charles de Gaulle-Etoile",
      4: "La Défense (Grande Arche)",
      5: "Nanterre-Université|Nanterre-Ville|Nanterre-Préfecture",
      6: "Rueil-Malmaison",
      8: "Chatou-Croissy",
      9: "Le Vésinet-Centre|Le Vésinet-Le Pecq|Saint-Germain-en-Laye",
    },
    18: {
      0: "Denfert-Rochereau",
      1: "Gentilly",
      2: "Arcueil-Cachan|Laplace",
      3: "Bagneux|Bourg-la-Reine",
      4: "La Croix-de-Berny|Parc de Sceaux",
      5: "Antony|Fontaine-Michalon|Les Baconnets",
      6: "Massy-Palaiseau|Massy-Verrières",
      7: "Palaiseau|Palaiseau Villebon",
      8: "Lozère",
      9: "Le Guichet|Orsay-Ville",
      10: "Bures-sur-Yvette|Courcelle-sur-Yvette|Gif-sur-Yvette|La Hacquinière|Saint-Rémy-lès-Chevreuse",
    },
    20: {
      1: "Gare de l'Est",
      4: "Pantin",
      5: "Noisy-le-Sec",
      6: "Bondy",
      7: "Gagny|Le Raincy Villemomble",
      9: "Chelles Gournay|Le Chênay Gagny",
      10: "Vaires Torcy",
      11: "Lagny-Thorigny",
      13: "Esbly",
      14: "Meaux",
      15: "Changis-Saint-Jean|Isles-Armentières Congis|Lizy-sur-Ourcq|Trilport",
      16: "Crouy-sur-Ourcq|La Ferté-sous-Jouarre|Nanteuil Saacy",
    },
    21: {
      5: "Rosny-Bois-Perrier|Rosny-sous-Bois|Val de Fontenay",
      6: "Nogent Le-Perreux",
      7: "Les Boullereaux Champigny",
      8: "Villiers-sur-Marne",
      9: "Les Yvris Noisy-le-Grand",
      10: "Emerainville|Roissy-en-Brie",
      11: "Ozoir-la-Ferrière",
      12: "Gretz-Armainvilliers|Tournan",
      15: "Courquetaine|Faremoutiers Pommeuse|Guerard La-Celle-sur-Morin|Liverdy en Brie|Marles-en-Brie|Mormant|Mortcerf|Mouroux|Ozouer le voulgis|Verneuil-l'Etang|Villepatour - Presles|Yebles|Yebles - Guignes",
      16: "Chailly Boissy-le-Châtel|Chauffry|Coulommiers|Jouy-sur-Morin Le-Marais|Nangis|Saint-Rémy-la-Vanne|Saint-Siméon",
      17: "Champbenoist-Poigny|La Ferté-Gaucher|Longueville|Provins|Sainte-Colombe-Septveilles",
      18: "Flamboin|Meilleray|Villiers St Georges",
    },
    22: {
      7: "Allée de la Tour-Rendez-Vous|La Remise-à-Jorelle|Les Coquetiers|Les Pavillons-sous-Bois",
      8: "Gargan",
      9: "Freinville Sevran|L'Abbaye|Lycée Henri Sellier|Rougemont-Chanteloup",
    },
    23: {
      13: "Couilly Saint-Germain Quincy|Les Champs-Forts|Montry Condé",
      14: "Crécy-en-Brie La Chapelle|Villiers-Montbarbin",
    },
    26: {
      5: "Val de Fontenay",
      6: "Bry-sur-Marne|Neuilly-Plaisance",
      7: "Noisy-le-Grand (Mont d'Est)",
      8: "Noisy-Champs",
      10: "Lognes|Noisiel|Torcy",
      11: "Bussy-Saint-Georges",
      12: "Val d'europe",
      13: "Marne-la-Vallée Chessy",
      16: "Goussainville",
    },
    28: {
      4: "Fontenay-aux-Roses|Robinson|Sceaux",
    },
    30: {
      1: "Gare Saint-Lazare",
      3: "Pont Cardinet",
      4: "Asnières|Bécon-les-Bruyères|Clichy Levallois|Courbevoie|La Défense (Grande Arche)",
      5: "Puteaux|Suresnes Mont-Valérien",
      7: "Garches Marne-la-Coquette|Le Val d'Or|Saint-Cloud",
      8: "Vaucresson",
      9: "Bougival|La Celle-Saint-Cloud|Louveciennes|Marly-le-Roi",
      10: "L'Etang-la-Ville|Saint-Nom-la-Bretêche Forêt",
    },
    31: {
      7: "Chaville-Rive Droite|Sèvres Ville-d'Avray|Viroflay-Rive Droite",
      8: "Montreuil|Versailles-Rive Droite",
    },
    32: {
      5: "La Garenne-Colombes|Les Vallées|Nanterre-Université",
      7: "Houilles Carrières-sur-Seine|Sartrouville",
      9: "Maisons-Laffitte",
      10: "Poissy",
      11: "Médan|Villennes-sur-Seine",
      12: "Les Clairières de Verneuil|Vernouillet Verneuil",
      13: "Aubergenville-Elisabethville|Les Mureaux",
      14: "Epône Mézières",
      16: "Bonnières|Mantes-la-Jolie|Mantes-Station|Port-Villez|Rosny-sur-Seine",
    },
    33: {
      10: "Achères-Grand-Cormier|Achères-Ville",
      11: "Cergy-Préfecture|Neuville-Université",
      12: "Cergy-le-Haut|Cergy-Saint-Christophe",
    },
    34: {
      5: "Suresnes - Lonchamp",
      6: "Les Côteaux|Pont de Saint Cloud|Pont de Sèvres",
      7: "Bas Meudon|Bellevue funiculaire",
      8: "Les Moulineaux - Billancourt",
    },
    35: {
      4: "Bois-Colombes",
      5: "Colombes|Le Stade",
      6: "Argenteuil",
      8: "Cormeilles-en-Parisis|Val d'Argenteuil",
      9: "Herblay|La Frette Montigny",
      10: "Conflans-Fin d'Oise|Conflans-Sainte-Honorine",
      11: "Andrésy|Chanteloup-lès-Vignes|Maurecourt",
      12: "Triel-sur-Seine|Vaux-sur-Seine",
      13: "Meulan Hadricourt|Thun-le-Paradis",
      14: "Gargenville|Juziers",
      15: "Issou Porcheville|Limay",
      16: "Breval|Ménerville",
    },
    40: {
      1: "Gare de Lyon|Gare de Lyon (Banlieue)",
      5: "Le Vert de Maisons|Maisons-Alfort Alfortville",
      6: "Villeneuve-Prairie",
      7: "Villeneuve-Triage",
      8: "Villeneuve-Saint-Georges",
      9: "Juvisy|Vigneux-sur-Seine",
      10: "Ris-Orangis|Viry-Châtillon",
      11: "Evry Val de Seine|Grand-Bourg",
      12: "Corbeil-Essonnes|Mennecy|Moulin-Galant",
      13: "Ballancourt|Fontenay le Vicomte",
      14: "La Ferté-Alais",
      16: "Boutigny|Maisse",
      17: "Boigneville|Buno-Gironville",
    },
    41: {
      0: "Saint-Michel Notre-Dame|Musée d'Orsay",
      1: "Gare d'Austerlitz",
      2: "Bibliotheque-Francois",
      3: "Boulevard Masséna",
      4: "Ivry-sur-Seine|Vitry-sur-Seine",
      5: "Choisy-le-Roi|Les Ardoines",
      7: "Villeneuve-le-Roi",
      8: "Ablon",
      9: "Athis-Mons",
    },
    42: {
      9: "Epinay-sur-Orge|Savigny-sur-Orge",
      10: "Sainte-Geneviève-des-Bois",
      11: "Saint-Michel-sur-Orge",
      12: "Brétigny-sur-Orge|Marolles-en-Hurepoix",
      13: "Bouray|Lardy",
      14: "Chamarande|Etampes|Etréchy",
      16: "Saint-Martin d'Etampes",
      17: "Guillerval",
    },
    43: {
      9: "Montgeron Crosne|Yerres",
      10: "Brunoy",
      11: "Boussy-Saint-Antoine|Combs-la-Ville Quincy",
      12: "Lieusaint Moissy",
      13: "Cesson|Savigny-le-Temple Nandy",
      15: "Le Mée|Melun",
      16: "Chartrettes|Fontaine-le-Port|Livry-sur-Seine",
      17: "Champagne-sur-Seine|Héricy|La Grande Paroisse|Vernou-sur-Seine|Vulaines-sur-Seine Samoreau",
    },
    44: {
      12: "Essonnes-Robinson|Villabé",
      13: "Coudray-Montceaux|Le Plessis-Chenet-IBM|Saint-Fargeau",
      14: "Boissise-le-Roi|Ponthierry Pringy",
      15: "Vosves",
      16: "Bois-le-Roi",
      17: "Bagneaux-sur-Loing|Bourron-Marlotte Grez|Fontainebleau-Avon|Montereau|Montigny-sur-Loing|Moret Veneux-les-Sablons|Nemours Saint-Pierre|Saint-Mammés|Souppes|Thomery",
    },
    45: {
      10: "Grigny-Centre",
      11: "Evry Courcouronnes|Orangis Bois de l'Epine",
      12: "Le Bras-de-Fer - Evry",
    },
    50: {
      0: "Haussmann-Saint-Lazare",
      1: "Gare du Nord|Gare du Nord (Surface)|Magenta|Paris-Nord",
      5: "Epinay-Villetaneuse|Saint-Denis|Sèvres-Rive Gauche",
      6: "La Barre-Ormesson",
      7: "Champ de Courses d'Enghien|Enghien-les-Bains",
      8: "Ermont Eaubonne|Ermont-Eaubonne|Ermont-Halte|Gros-Noyer Saint-Prix",
      9: "Saint-Leu-La-Forêt|Taverny|Vaucelles",
      10: "Bessancourt|Frépillon|Mery",
      11: "Mériel|Valmondois",
      12: "Bruyères-sur-Oise|Champagne-sur-Oise|L'Isle-Adam Parmain|Persan Beaumont",
    },
    51: {
      4: "La Courneuve-Aubervilliers|La Plaine-Stade de France",
      5: "Le Bourget",
      7: "Blanc-Mesnil|Drancy",
      8: "Aulnay-sous-Bois",
      9: "Sevran Livry|Vert-Galant",
      10: "Villeparisis",
      11: "Compans|Mitry Claye|Mitry-Claye",
      12: "Dammartin Juilly Saint-Mard|Thieux Nantouillet",
    },
    52: {
      5: "Stade de France-Saint-Denis",
      6: "Pierrefitte Stains",
      7: "Garges-Sarcelles",
      8: "Villiers-le-Bel (Gonesse -",
      10: "Goussainville|Les Noues|Louvres",
      11: "La Borne-Blanche|Survilliers-Fosses",
    },
    53: {
      6: "Deuil Montmagny",
      7: "Groslay",
      8: "Sarcelles Saint-Brice",
      9: "Domont|Ecouen Ezanville",
      10: "Bouffemont Moisselles|Montsoult Maffliers",
      11: "Belloy-Saint-Martin|Luzarches|Seugy|Viarmes|Villaines",
    },
    54: {
      8: "Cernay",
      9: "Franconville|Montigny Beauchamp|Montigny-Beauchamp",
      10: "Pierrelaye",
      11: "Pontoise|Saint-Ouen-l'Aumône|Saint-Ouen-l'Aumone-Liesse",
      12: "Boissy-l'Aillerie|Osny",
      15: "Chars|Montgeroult Courcelles|Santeuil Le Perchay|Us",
    },
    55: {
      0: "Avenue Foch|Avenue Henri-Martin|Kennedy Radio-France|Boulainvilliers|Neuilly-Porte Maillot",
      1: "Péreire-Levallois",
      2: "Porte de Clichy",
      3: "Saint-Ouen",
      4: "Les Grésillons",
      5: "Gennevilliers",
      6: "Epinay-sur-Seine",
      7: "Saint-Gratien",
    },
    56: {
      11: "Auvers-sur-Oise|Chaponval|Epluches|Pont Petit",
    },
    57: {
      11: "Presles Courcelles",
      12: "Nointel Mours",
    },
    60: {
      1: "Gare Montparnasse|Paris Montparnasse3 Vaug.",
      4: "Clamart|Vanves Malakoff",
      5: "Bellevue|Bièvres|Meudon",
      6: "Chaville-Rive Gauche|Chaville-Vélizy|Viroflay-Rive Gauche",
      7: "Versailles-Chantiers",
      10: "Saint-Cyr",
      11: "Saint-Quentin-en-Yvelines -|Trappes",
      12: "Coignières|La Verrière",
      13: "Les Essarts-le-Roi",
      14: "Le Perray|Rambouillet",
      15: "Gazeran",
    },
    61: {
      10: "Fontenay-le-Fleury",
      11: "Villepreux Les-Clayes",
      12: "Plaisir Grignon|Plaisir Les-Clayes",
      13: "Beynes|Mareil-sur-Mauldre|Maule|Nézel Aulnay",
      15: "Garancières La-Queue|Montfort-l'Amaury Méré|Orgerus Behoust|Tacoignères Richebourg|Villiers Neauphle",
      16: "Houdan",
    },
    63: {
      7: "Porchefontaine|Versailles-Rive Gauche",
    },
    64: {
      0: "Pont de l'alma|Invalides",
      1: "Champ de Mars-Tour Eiffel",
      2: "Javel",
      3: "Boulevard Victor - Pont du Garigliano",
      4: "Issy-Val de Seine",
      5: "Issy|Meudon-Val-Fleury",
    },
    65: {
      8: "Jouy-en-Josas|Petit-Jouy-les-Loges",
      9: "Vauboyen",
      10: "Igny",
      11: "Massy-Palaiseau",
      12: "Longjumeau",
      13: "Chilly-Mazarin",
      14: "Gravigny-Balizy|Petit-Vaux",
    },
    70: {
      9: "Parc des Expositions|Sevran-Beaudottes|Villepinte",
      10: "Aéroport Charles de Gaulle 1|Aéroport Charles de Gaulle 2",
    },
    72: {
      7: "Sannois",
    },
    73: {
      11: "Eragny Neuville|Saint-Ouen-l'Aumône (Eglise)",
    },
    75: {
      7: "Les Saules|Orly-Ville",
      9: "Pont de Rungis Aéroport|Rungis-La Fraternelle",
      10: "Chemin d'Antony",
      12: "Massy-Verrières",
    },
    76: {
      12: "Arpajon|Egly|La Norville",
      13: "Breuillet Bruyères-le-Châtel|Breuillet-Village|Saint-Chéron",
      14: "Sermaise",
      15: "Dourdan|Dourdan-la-Forêt",
    },
  };

  public static dataMetro: Dictionary<Dictionary<string>> = {
    1: {
      1: "Saint-Michel",
      4: "Odéon",
      5: "Cluny - La Sorbonne",
      6: "Maubert - Mutualité",
      7: "Luxembourg",
      8: "Châtelet",
      9: "Les Halles",
      10: "Les Halles",
      12: "Louvre - Rivoli",
      13: "Pont Neuf",
      14: "Cité",
      15: "Hôtel de Ville",
    },
    2: {
      2: "Cambronne",
      3: "Sèvres - Lecourbe",
      4: "Ségur",
      6: "Saint-François-Xavier",
      7: "Duroc",
      8: "Vaneau",
      9: "Sèvres - Babylone",
      10: "Rue du Bac",
      11: "Rennes",
      12: "Saint-Sulpice",
      14: "Mabillon",
      15: "Saint-Germain-des-Prés",
    },
    3: {
      4: "Porte de la Villette",
      5: "Aubervilliers - Pantin - Quatre Chemins",
      6: "Fort d'Aubervilliers",
      7: "La Courneuve - 8 Mai 1945",
      9: "Hoche",
      10: "Église de Pantin",
      11: "Bobigny - Pantin - Raymond Queneau",
      12: "Bobigny - Pablo Picasso",
    },
    4: {
      2: "Pernety",
      3: "Plaisance",
      4: "Gaîté",
      6: "Edgar Quinet",
      7: "Vavin",
      8: "Montparnasse - Bienvenüe",
      12: "Saint-Placide",
      14: "Notre-Dame-des-Champs",
    },
    5: {
      2: "Robespierre",
      3: "Porte de Montreuil",
      4: "Maraîchers",
      5: "Buzenval",
      6: "Rue des Boulets",
      7: "Porte de Vincennes",
      9: "Picpus",
      10: "Nation",
      12: "Avron",
      13: "Alexandre Dumas",
    },
    6: {
      1: "Malesherbes",
      2: "Monceau",
      3: "Villiers",
      4: "Quatre-Septembre",
      5: "Opéra",
      6: "Auber",
      7: "Havre - Caumartin",
      8: "Saint-Lazare",
      9: "Saint-Lazare",
      10: "Saint-Augustin",
      12: "Europe",
      13: "Liège",
    },
    7: {
      3: "Porte de Saint-Cloud",
      7: "Porte d'Auteuil",
      8: "Église d'Auteuil",
      9: "Michel-Ange - Auteuil",
      10: "Michel-Ange - Molitor",
      11: "Chardon-Lagache",
      12: "Mirabeau",
      14: "Exelmans",
      15: "Jasmin",
    },
    8: {
      1: "Rambuteau",
      3: "Arts et Métiers",
      4: "Jacques Bonsergent",
      5: "Goncourt",
      6: "Temple",
      7: "République",
      10: "Oberkampf",
      11: "Parmentier",
      12: "Filles du Calvaire",
      13: "Saint-Sébastien - Froissart",
      14: "Richard-Lenoir",
      15: "Saint-Ambroise",
    },
    9: {
      1: "Quai de la Gare",
      2: "Chevaleret",
      4: "Saint-Marcel",
      7: "Gare d'Austerlitz",
      8: "Gare de Lyon",
      10: "Quai de la Rapée",
    },
    10: {
      1: "Champs-Élysées - Clemenceau",
      2: "Concorde",
      3: "Madeleine",
      4: "Bir-Hakeim",
      7: "École Militaire",
      8: "La Tour-Maubourg",
      9: "Invalides",
      11: "Saint-Denis - Université",
      12: "Varenne",
      13: "Assemblée nationale",
      14: "Solférino",
    },
    11: {
      1: "Tuileries",
      2: "Palais Royal - Musée du Louvre",
      3: "Pyramides",
      4: "Bourse",
      6: "Grands Boulevards",
      7: "Richelieu - Drouot",
      8: "Bonne Nouvelle",
      10: "Strasbourg - Saint-Denis",
      11: "Château d'Eau",
      13: "Sentier",
      14: "Réaumur - Sébastopol",
      15: "Étienne Marcel",
    },
    12: {
      1: "Faidherbe - Chaligny",
      2: "Reuilly - Diderot",
      3: "Montgallet",
      4: "Censier - Daubenton",
      5: "Place Monge",
      6: "Cardinal Lemoine",
      7: "Jussieu",
      8: "Sully - Morland",
      9: "Pont Marie",
      10: "Saint-Paul",
      12: "Bastille",
      13: "Chemin Vert",
      14: "Bréguet - Sabin",
      15: "Ledru-Rollin",
    },
    13: {
      1: "Porte Dorée",
      3: "Porte de Charenton",
      7: "Bercy",
      8: "Dugommier",
      10: "Michel Bizot",
      11: "Daumesnil",
      12: "Bel-Air",
    },
    14: {
      2: "Porte de Choisy",
      3: "Porte d'Italie",
      4: "Cité universitaire",
      9: "Maison Blanche",
      10: "Tolbiac",
      11: "Nationale",
      12: "Campo-Formio",
      13: "Les Gobelins",
      14: "Place d'Italie",
      15: "Corvisart",
    },
    15: {
      1: "Cour Saint-Emilion",
      2: "Porte d'Orléans",
      3: "Bibliothèque François Mitterrand",
      4: "Mouton-Duvernet",
      5: "Alésia",
      6: "Olympiades",
      8: "Glacière",
      9: "Saint-Jacques",
      10: "Raspail",
      14: "Denfert-Rochereau",
    },
    16: {
      1: "Falguière",
      2: "Pasteur",
      3: "Volontaires",
      4: "Vaugirard",
      5: "Convention",
      6: "Porte de Versailles",
      9: "Balard",
      10: "Lourmel",
      11: "Boucicaut",
      12: "Félix Faure",
      13: "Charles Michels",
      14: "Javel - André Citroën",
    },
    17: {
      2: "Porte Dauphine",
      4: "La Motte-Picquet - Grenelle",
      5: "Commerce",
      6: "Avenue Émile Zola",
      7: "Dupleix",
      8: "Passy",
      9: "Ranelagh",
      11: "La Muette",
      13: "Rue de la Pompe",
      14: "Boissière",
      15: "Trocadéro",
    },
    18: {
      1: "Iéna",
      3: "Alma - Marceau",
      4: "Miromesnil",
      5: "Saint-Philippe du Roule",
      7: "Franklin D. Roosevelt",
      8: "George V",
      9: "Kléber",
      10: "Victor Hugo",
      11: "Argentine",
      12: "Charles de Gaulle - ?~Itoile",
      14: "Ternes",
      15: "Courcelles",
    },
    19: {
      1: "Mairie de Clichy",
      2: "Gabriel Péri",
      3: "Les Agnettes",
      4: "Asnières - Gennevilliers - Les Courtilles",
      9: "La Chapelle)",
      10: "Garibaldi",
      11: "Mairie de Saint-Ouen",
      13: "Carrefour Pleyel",
      14: "Saint-Denis - Porte de Paris",
      15: "Basilique de Saint-Denis",
    },
    20: {
      1: "Porte de Clignancourt",
      6: "Porte de la Chapelle",
      7: "Marx Dormoy",
      9: "Marcadet - Poissonniers",
      10: "Simplon",
      11: "Jules Joffrin",
      12: "Lamarck - Caulaincourt",
    },
    21: {
      1: "Chaussée d'Antin - La Fayette",
      2: "Le Peletier",
      3: "Cadet",
      4: "Château Rouge",
      7: "Barbès - Rochechouart",
      8: "Gare du Nord",
      9: "Gare de l'Est",
      10: "Poissonnière",
      11: "Château-Landon",
    },
    22: {
      1: "Porte de Pantin",
      2: "Ourcq",
      4: "Corentin Cariou",
      6: "Crimée",
      8: "Riquet",
      9: "La Chapelle",
      10: "Louis Blanc",
      11: "Stalingrad",
      12: "Jaurès",
      13: "Laumière",
      14: "Bolivar",
      15: "Colonel Fabien",
    },
    23: {
      2: "Porte des Lilas",
      3: "Mairie des Lilas",
      4: "Porte de Bagnolet",
      5: "Gallieni",
      8: "Place des Fêtes",
      9: "Botzaris",
      10: "Danube",
      11: "Pré Saint-Gervais",
      13: "Buttes Chaumont",
      14: "Jourdain",
      15: "Télégraphe",
    },
    24: {
      1: "Voltaire",
      2: "Charonne",
      4: "Père Lachaise",
      5: "Ménilmontant",
      6: "Rue Saint-Maur",
      7: "Philippe Auguste",
      8: "Saint-Fargeau",
      9: "Pelleport",
      10: "Gambetta",
      12: "Belleville",
      13: "Couronnes",
      14: "Pyrénées",
    },
    25: {
      2: "Croix de Chavaux",
      3: "Mairie de Montreuil",
      4: "Maisons-Alfort - Les Juilliottes",
      5: "Créteil - L'Échat",
      6: "Créteil - Université",
      7: "Créteil - Préfecture",
      8: "Saint-Mandé",
      10: "Bérault",
      11: "Château de Vincennes",
      12: "Liberté",
      13: "Charenton - Écoles",
      14: "École vétérinaire de Maisons-Alfort",
      15: "Maisons-Alfort - Stade",
    },
    26: {
      3: "Porte d'Ivry",
      4: "Pierre et Marie Curie",
      5: "Mairie d'Ivry",
      6: "Le Kremlin-Bicêtre",
      7: "Villejuif - Léo Lagrange",
      8: "Villejuif - Paul Vaillant-Couturier",
      9: "Villejuif - Louis Aragon",
    },
    27: {
      2: "Porte de Vanves",
      7: "Malakoff - Plateau de Vanves",
      8: "Malakoff - Rue Étienne Dolet",
      9: "Châtillon - Montrouge",
    },
    28: {
      2: "Corentin Celton",
      3: "Mairie d'Issy",
      8: "Marcel Sembat",
      9: "Billancourt",
      10: "Pont de Sèvres",
    },
    29: {
      0: "La Défense (correspondance RER)",
      4: "Boulogne - Jean Jaurès",
      5: "Boulogne - Pont de Saint-Cloud",
      8: "Les Sablons",
      9: "Pont de Neuilly",
      10: "Esplanade de la Défense",
      11: "La Défense",
      12: "Porte de Champerret",
      13: "Louise Michel",
      14: "Anatole France",
      15: "Pont de Levallois - Bécon",
    },
    30: {
      1: "Porte Maillot",
      4: "Wagram",
      5: "Pereire",
      8: "Brochant",
      9: "Porte de Clichy",
      12: "Guy Môquet",
      13: "Porte de Saint-Ouen",
    },
    31: {
      2: "Funiculaire de Montmartre (station inférieure)",
      3: "Funiculaire de Montmartre (station supérieure)",
      4: "Anvers",
      5: "Abbesses",
      6: "Pigalle",
      7: "Blanche",
      8: "Trinité - d'Estienne d'Orves",
      9: "Notre-Dame-de-Lorette",
      10: "Saint-Georges",
      12: "Rome",
      13: "Place de Clichy",
      14: "La Fourche",
    },
  };

  public static dataBusUrbain: Dictionary<Dictionary<string>> = {
    0: {
      10: "Leon Cassé (Corbeil Essonnes)",
      16: "Cergy Saint Christophe RER",
      21: "Léon Cassé (Corbeil Essonnes)",
      27: "Porte des Lilas",
      28: "Marcel Cerdan (Goussainville)",
    },
    2: {
      18: "Aéroville (Tremblay-en-France)",
    },
    49: {
      6: "Roissypôle (Tremblay-en-France)",
    },
  };

  public static dataTramway: Dictionary<Dictionary<string>> = {
    0: {
      1: "Porte des Lilas",
      25: "Meudon la Forêt",
    },
    20: {
      6: "Bondy",
    },
    64: {
      0: "La Belle Épine",
      1: "Porte de l'Essonne",
      2: "Ella Fitzgerald",
    },
    65: {
      29: "Gare de Jusivy RER",
    },
    122: {
      28: "Porte de Choisy",
    },
  };

  public getStation(codeEvent: number, locationId: number): string {
    const modeCode = Math.floor(codeEvent / 16);

    const locationZone = locationId >> 9; //0-6
    const locationStation = (locationId >> 4) % 32; //7-11
    const locationInconnu = locationId % 16; //12-15 ???
    console.info(`${locationId} => zone : ${locationZone} - Station : ${locationStation} - ?? : ${locationInconnu}`);

    switch (modeCode) {
      case Mode.BusUrbain:
        if (Station.dataBusUrbain[locationZone] !== undefined && Station.dataBusUrbain[locationZone][locationStation] !== undefined)
          return Station.dataBusUrbain[locationZone][locationStation];
      case Mode.Train:
        if (Station.dataTrain[locationZone] !== undefined && Station.dataTrain[locationZone][locationStation] !== undefined)
          return Station.dataTrain[locationZone][locationStation];
      case Mode.Metro:
        if (Station.dataMetro[locationZone] !== undefined && Station.dataMetro[locationZone][locationStation] !== undefined)
          return Station.dataMetro[locationZone][locationStation];
      case Mode.Tramway:
        if (Station.dataTramway[locationZone] !== undefined && Station.dataTramway[locationZone][locationStation] !== undefined)
          return Station.dataTramway[locationZone][locationStation];
    }

    return "Station inconnue (" + codeEvent + "-" + locationId + ")";
  }
}
